<a href="https://colab.research.google.com/github/wonejomcoesr/ejercicios_propuestos/blob/main/Clases_17_07_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tipos de datos**

In [1]:
import numpy as np
#Enteros
np.int64

numpy.int64

In [2]:
#Decimales, flotantes
np.float64

numpy.float64

In [3]:
#Numeros complejos, variables complejas
np.complex64

numpy.complex64

In [4]:
#Booleanos
np.bool #tipo de dato antiguo
np.bool_ #tipo de dato mas nuevo

numpy.bool

In [5]:
#Objetos
np.object_

numpy.object_

In [8]:
#Cadenas de texto
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [9]:
#Bytes
np.bytes_

numpy.bytes_

**Propiedades y caracteristicas de entornos**

In [23]:
#Codigo de la clase anterior, array_3d
array_3d=np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=np.double)
array_3d


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [33]:
#Array de 5 dimensiones
array_5d = np.random.rand(2, 2, 3, 3, 5)

In [11]:
#Muestra la dimension
array_3d.shape

(3, 3)

In [12]:
#Longitud de datos (solo muestra la longitud mayor)
len(array_3d)

3

In [34]:
#Numero de dimensiones
array_5d.ndim

5

In [35]:
#Tipos de datos (ver el tipo de dato que se tiene)
array_3d.dtype

dtype('float64')

In [36]:
array_3d.dtype.name

'float64'

In [41]:
#Convertir tipos de datos de float a int
array_3d.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Operadores matematicos**

In [42]:
#Array de ejemplos
array1=np.random.random((4,4))
array1

array([[0.22629658, 0.92714114, 0.83236577, 0.33999192],
       [0.7919004 , 0.84515726, 0.99752406, 0.82098996],
       [0.46446017, 0.29550289, 0.97572258, 0.4390457 ],
       [0.22423193, 0.49606275, 0.17437675, 0.49022997]])

In [43]:
array2=np.random.random((4,4))
array2

array([[0.56324222, 0.75928696, 0.64370366, 0.48989452],
       [0.62857726, 0.10331972, 0.41011693, 0.90811154],
       [0.82347722, 0.39695491, 0.41404424, 0.42811069],
       [0.13858239, 0.89068291, 0.19522472, 0.05230161]])

In [44]:
array3=np.random.random((4,4))
array3

array([[0.84409737, 0.14873312, 0.78614944, 0.10913615],
       [0.85492453, 0.33461354, 0.12957622, 0.81323174],
       [0.86570618, 0.51520155, 0.86678142, 0.6251542 ],
       [0.69987959, 0.04284333, 0.94775037, 0.10326525]])

In [45]:
#Suma
array4=array1+array2+array3
array4

array([[1.63363618, 1.83516123, 2.26221887, 0.93902259],
       [2.27540219, 1.28309052, 1.53721721, 2.54233324],
       [2.15364357, 1.20765935, 2.25654824, 1.49231059],
       [1.06269391, 1.42958899, 1.31735184, 0.64579683]])

In [46]:
#Otra forma de sumar array´s
array4=np.add(array1,array2,array3)
array4

array([[0.78953881, 1.6864281 , 1.47606943, 0.82988643],
       [1.42047766, 0.94847698, 1.40764099, 1.7291015 ],
       [1.28793739, 0.6924578 , 1.38976683, 0.86715639],
       [0.36281432, 1.38674567, 0.36960147, 0.54253158]])

In [57]:
#Resta
#array4=array1-array2+array3
#array4

array4=np.subtract(array1,array2,array3)

In [49]:
#Multiplicacion
array4=np.multiply(array1,array2,array3)
array4

array([[0.12745979, 0.70396618, 0.53579689, 0.16656018],
       [0.49777059, 0.08732141, 0.4091015 , 0.74555046],
       [0.38247237, 0.11730132, 0.40399232, 0.18796016],
       [0.0310746 , 0.44183462, 0.03404265, 0.02563982]])

In [59]:
#Division
array4=np.divide(array1,array2,array3)
array4

array([[0.40177489, 1.22106817, 1.29308847, 0.69401045],
       [1.25982985, 8.18001873, 2.43229186, 0.90406291],
       [0.5640231 , 0.74442434, 2.35656599, 1.02554247],
       [1.6180406 , 0.55694652, 0.89321037, 9.3731326 ]])

In [60]:
#Exponentes
np.exp(array1)

array([[1.25394751, 2.52727372, 2.29875064, 1.40493623],
       [2.20758774, 2.32834394, 2.71155985, 2.27274866],
       [1.59115501, 1.34380198, 2.65308359, 1.55122617],
       [1.25136122, 1.64224261, 1.190504  , 1.63269164]])

In [61]:
#Operadores trigonometricos
#Seno
np.sin(array1)

array([[0.22437007, 0.79990754, 0.73952591, 0.33347947],
       [0.71168958, 0.74807548, 0.84013065, 0.73182085],
       [0.44794023, 0.29122098, 0.82810716, 0.42507586],
       [0.22235759, 0.47596657, 0.17349437, 0.47082878]])

In [62]:
#Coseno
np.cos(array2)

array([[0.84552844, 0.72532705, 0.79987845, 0.8823825 ],
       [0.80886489, 0.99466726, 0.91707421, 0.6152356 ],
       [0.67967474, 0.92224254, 0.91550125, 0.90975172],
       [0.99041282, 0.62888121, 0.9810041 , 0.99863258]])

In [66]:
#Logaritmos
np.log(array3)
array3

/tmp/ipython-input-66-2175532414.py:2: RuntimeWarning: invalid value encountered in log
  np.log(array3)


array([[-0.33694564,  0.16785418,  0.18866212, -0.1499026 ],
       [ 0.16332314,  0.74183754,  0.58740713, -0.08712158],
       [-0.35901704, -0.10145201,  0.56167834,  0.010935  ],
       [ 0.08564954, -0.39462016, -0.02084798,  0.43792835]])

**Comparaciones entre matrices**

In [65]:
# ==
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [68]:
# <
array1<0.5

array([[ True, False, False,  True],
       [False, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [70]:
array2 >= 0.4

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [False,  True, False, False]])

**Estadistica y funciones**

In [71]:
array6=np.random.random((5,5))
array6

array([[0.06843397, 0.36653125, 0.59182795, 0.80221601, 0.80196407],
       [0.73358042, 0.8417394 , 0.67668648, 0.82980337, 0.73962578],
       [0.80385396, 0.56326764, 0.62932439, 0.03071433, 0.18745624],
       [0.34687683, 0.11120435, 0.29644598, 0.75680947, 0.09197658],
       [0.05523348, 0.07749382, 0.71121048, 0.91753884, 0.71367097]])

In [72]:
#Suma de elementos
sumatotal=array6.sum()
print(sumatotal)

12.745486039868261


In [73]:
#Valor minimo-maximo
array6.min()
array6.max()

np.float64(0.9175388421032866)

In [76]:
#Maximo por fila/columna
array6.max(axis=0)

array([0.80385396, 0.8417394 , 0.71121048, 0.91753884, 0.80196407])

In [77]:
#Fila acumulada
array6.cumsum(axis=1)

array([[0.06843397, 0.43496522, 1.02679317, 1.82900918, 2.63097325],
       [0.73358042, 1.57531982, 2.2520063 , 3.08180967, 3.82143544],
       [0.80385396, 1.3671216 , 1.99644599, 2.02716031, 2.21461655],
       [0.34687683, 0.45808117, 0.75452715, 1.51133662, 1.6033132 ],
       [0.05523348, 0.1327273 , 0.84393778, 1.76147662, 2.47514759]])

In [78]:
#Media
np.mean(array6)

np.float64(0.5098194415947305)

In [79]:
#Mediana
np.median(array6)

np.float64(0.6293243898552523)

In [80]:
#Desviacion standar
np.std(array6)

np.float64(0.3021081641254775)